### PR TITLE
add missing bracket

### PR DESCRIPTION
**Pull request by roman3017**

### CODE REVIEW

**Comment by ZipCPU** [comment]
Thank you!

**Comment by roman3017** [comment]
Thank you for great tutorials.

**Comment by ZipCPU** [comment]
I don't get this though... my local repository doesn't have the missing bracket, while the github repository did?  git status says nothing's changed since my last push.  I must be missing some git foo something or other.

**Comment by roman3017** [comment]
I can see the change:
```sh
$ git log
commit 59b24816ec1b56cf45b0b1416a910faf7a32d69a (HEAD -> master, origin/master, origin/HEAD)
Merge: dcd5134 a23dd64
Author: Dan Gisselquist <dgisselq@ieee.org>
Date:   Thu Nov 29 13:38:48 2018 -0500

    Merge pull request #1 from roman3017/master
    
    add missing bracket

commit a23dd64e6fa3604b8b78e26e488e82f54507a5a7 (roman/master)
Author: roman3017 <rbacik@hotmail.com>
Date:   Thu Nov 29 09:36:17 2018 -0800

    add missing bracket

commit dcd5134b7f411c06c1d8b83b1c27404e95e93861
Author: ZipCPU <dgisselq@ieee.org>
Date:   Thu Nov 29 10:38:04 2018 -0500

    Upgraded all the formal proofs to use SymbiYosys

commit e163bfc45f44bc1fea1cf5a491af54fa7d6cb564
```
```diff
$ git diff HEAD~
diff --git a/rtl/vgatestsrc.v b/rtl/vgatestsrc.v
index ff3089c..5c542e8 100644
--- a/rtl/vgatestsrc.v
+++ b/rtl/vgatestsrc.v
@@ -126,7 +126,7 @@ module      vgatestsrc(i_pixclk, i_reset,
 
        initial hpos  = 0;
        initial hbar  = 0;
-       initial hedge = { 4'h0, i_width[(HW-1):4];
+       initial hedge = { 4'h0, i_width[(HW-1):4] };
        always @(posedge i_pixclk)
        if ((i_reset)||(i_newline))
        begin
```

**Pull request merged**
